#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'

def build hash, dir
	dir.each_child do |child|
		if Dir.exist? file_name = "#{dir.path}/#{child}"
			build hash[child] = {}, Dir.new(file_name)
		else
			hash[child] = 'f'
		end
	end
end

dist = ARGV.first
result = { dist => {} }
build result[dist], Dir.new(dist)
open filename = "#{dist}/map.json", 'w+' do |file|
	file.puts JSON.generate result
end
system "git add #{filename}"
