name: Deploy to pages

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Buid libs
        uses: ./.github/actions/build-libs

      - name: Configure Pages
        id: pages
        uses: actions/configure-pages@v6

      - name: Jekyll build
        run: bundle exec rake
        env:
          JEKYLL_URL: ${{ steps.pages.outputs.origin }}
          JEKYLL_BASEURL: ${{ steps.pages.outputs.base_path }}
          JEKYLL_DOMAIN: ${{ steps.pages.outputs.host }}
          GITHUB_RUN_ID: ${{ github.run_id }}

      - name: Upload
        uses: actions/upload-pages-artifact@v5

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy
        id: deploy
        uses: actions/deploy-pages@v5
