# Cache not accessed for 7 days will be evicted by GitHub.
# The purpose of this workflow is to prevent that.
name: Refresh cache

on:
  workflow_dispatch:
  schedule:
    - cron: '11 8 */6 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7

      - name: Build libs
        uses: ./.github/actions/build-libs
