# Cache not accessed for 7 days will be evicted by GitHub.
# The purpose of this workflow is to prevent that.
name: Refresh cache

on:
  workflow_dispatch: {}
  schedule:
    - cron: '11 8 */6 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          submodules: recursive

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        id: setup-ruby
        with:
          ruby-version: '4.0'
          bundler-cache: true

      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version: '26'
          cache: npm
          cache-dependency-path: '**/package-lock.json'

      - name: Set up GHC
        uses: haskell-actions/setup@v2
        id: setup-ghc
        with:
          ghc-version: '9.10'

      - name: Restore Cabal cache
        uses: actions/cache/restore@v6
        id: cabal-cache-restore
        with:
          path: |
            ~/.cabal/packages
            ${{ steps.setup-ghc.outputs.cabal-store }}
            _lib/pandoc-bridge/dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/cabal.project.freeze') }}

      - name: Update Cabal package index
        if: steps.cabal-cache-restore.outputs.cache-hit != 'true'
        run: cabal update

      - name: Build libraries
        run: bundle exec rake build_libs

      - name: Save Cabal cache
        uses: actions/cache/save@v6
        if: steps.cabal-cache-restore.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cabal/packages
            ${{ steps.setup-ghc.outputs.cabal-store }}
            _lib/pandoc-bridge/dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('**/cabal.project.freeze') }}
